# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    upper_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - UPBODY_leftarm_1
      - UPBODY_leftarm_2
      - UPBODY_leftarm_3
      - UPBODY_leftarm_4
      - UPBODY_leftarm_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - UPBODY_rightarm_1
      - UPBODY_rightarm_2
      - UPBODY_rightarm_3
      - UPBODY_rightarm_4
      - UPBODY_rightarm_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
head_controller:
  ros__parameters:
    joints:
      - UPBODY_neck_1
      - UPBODY_neck_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
torso_controller:
  ros__parameters:
    joints:
      - BASE_body
      - body_1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
upper_body_controller:
  ros__parameters:
    joints:
      - BASE_body
      - body_1
      - UPBODY_leftarm_1
      - UPBODY_leftarm_2
      - UPBODY_leftarm_3
      - UPBODY_leftarm_4
      - UPBODY_leftarm_5
      - UPBODY_neck_1
      - UPBODY_neck_2
      - UPBODY_rightarm_1
      - UPBODY_rightarm_2
      - UPBODY_rightarm_3
      - UPBODY_rightarm_4
      - UPBODY_rightarm_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity